### ISSUE TITLE
Error: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by moarph** [jacotec/FreePBX-Superfecta-Tellows#1]
I'll get an errormessage:
`{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Trying to access array offset on value of type null","file":"\/var\/www\/html\/admin\/modules\/superfecta\/sources\/source-TellowsAPI.module","line":51}}`

Details (private things Xed):
Executing TellowsAPI
Request without API key
Orignal Raw Returned Data:
`{"tellows":{"number":"07121XXXXXXX","normalizedNumber":"07121-XXXXXXX","score":"5","searches":"8","comments":"0","scoreColor":"#d6ff18","scorePath":"https:\/\/www.tellows.de\/images\/score\/score5.png","location":"Reutlingen","country":"Deutschland","numberDetails":{"name":"XXXXXXX GmbH","category":"","street":"XXXXXXX","zipcode":"XXXXX","city":"","isCompany":"1"}}}Partner Data not correct`

php-json is installed on server. What else am i missing?

**Comment by jacotec** [comment]
Looks like Tellows starts to lock down unauthorized access to their API, they now break the JSON response format when the API number is not present or wrong with the "Partner Data not correct"

I think I'll remove the access without API key and try to find a way to deal with the broken response in case the entered API key is wrong

**Comment by moarph** [comment]
Well the thing is that the results I'm getting are correct. I have no problem paying for the API but right know I'm not sure if thats really the problem or not.

**Comment by jacotec** [comment]
@moarph Fixed with commit c892575. Requests with wrong or missing API key are not causing an error anymore but a debug message to check the API key.

Although the broken response without an API key (or with an invalid one) still contains the information, I'll not work around this because:

- I expect that the block will be corrected at some point to not contain any information anymore
- Most important point: The API is not intended by Tellows to work without a valid key. I've asked Tellows if the API request without a valid key is legitimate and they responded that it should not work without a valid key. Seems they have now made a first attempt to fix this.
They need to feed their families as well and €20 for 2 years private use is really a no-brainer.
